version: '2'

services:
  composer:
    build:
      context: composer
    # This fixes a strange bug with:
    # ERROR: for dnsmasq  Cannot start service dnsmasq: b'Address already in use'
    depends_on:
      - nginx
    volumes:
      - /usr/local/bin

  dnsmasq:
    build:
      context: dnsmasq
    cap_add:
      - NET_ADMIN
    command:
      - --address=/localhost/172.31.31.3
      - --local-service
      - --log-queries
      - --no-dhcp-interface=*
    networks:
      default:
        ipv4_address: &dnsmasq-ipv4-address 172.31.31.2

  nginx:
    build:
      context: nginx
      args:
        - USER_ID
        - GROUP_ID
    networks:
      default:
        ipv4_address: 172.31.31.3
    ports:
      - "80:80"
    volumes:
      - /dev/log:/dev/log
      - /run/php
      - ~/www:/www

  php-fpm-56:
    build:
      context: php-fpm-56
      args:
        - USER_ID
        - GROUP_ID
    dns:
      - *dnsmasq-ipv4-address
    networks:
      - default
    volumes_from:
      - composer
      - nginx

  php-fpm-71:
    build:
      context: php-fpm-71
      args:
        - USER_ID
        - GROUP_ID
    dns:
      - *dnsmasq-ipv4-address
    networks:
      - default
    volumes_from:
      - composer
      - nginx

  php-fpm-72:
    build:
      context: php-fpm-72
      args:
        - USER_ID
        - GROUP_ID
    dns:
      - *dnsmasq-ipv4-address
    networks:
      - default
    volumes_from:
      - composer
      - nginx

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.31.0/24
          gateway: 172.31.31.1
