version: '2'

services:
  composer:
    build:
      context: composer
    volumes:
      - /usr/local/bin

  nginx:
    build:
      context: nginx
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - /dev/log:/dev/log
      - /run/php
      - ~/www:/www

  php-fpm-56:
    build:
      context: php-fpm-56
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    volumes_from:
      - composer
      - nginx

  php-fpm-71:
    build:
      context: php-fpm-71
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    volumes_from:
      - composer
      - nginx

  php-fpm-72:
    build:
      context: php-fpm-72
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    volumes_from:
      - composer
      - nginx

networks:
  main:
    driver: bridge
