version: '2'

services:
  nginx:
    build:
      context: nginx
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - ~/www:/www
      - /run/php

  php-fpm-56:
    build:
      context: php-fpm-56
      args:
        - USER_ID
        - GROUP_ID
    networks:
      - main
    volumes_from:
      - nginx

networks:
  main:
    driver: bridge
